import { Roboto } from 'next/font/google'
import './globals.css'
import Headers from '@/components/Headers'
const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['cyrillic', 'latin']
 })

export const metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Headers/>
        <main className='container'>
        {children}
        </main>
        </body>
    </html>
  )
}
